// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/xuewentao/cheya/apps/vehicle/ent/schema"
	"github.com/xuewentao/cheya/apps/vehicle/ent/vehicle"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescVin is the schema descriptor for vin field.
	vehicleDescVin := vehicleFields[0].Descriptor()
	// vehicle.VinValidator is a validator for the "vin" field. It is called by the builders before save.
	vehicle.VinValidator = vehicleDescVin.Validators[0].(func(string) error)
	// vehicleDescLicensePlate is the schema descriptor for license_plate field.
	vehicleDescLicensePlate := vehicleFields[1].Descriptor()
	// vehicle.LicensePlateValidator is a validator for the "license_plate" field. It is called by the builders before save.
	vehicle.LicensePlateValidator = vehicleDescLicensePlate.Validators[0].(func(string) error)
	// vehicleDescStatus is the schema descriptor for status field.
	vehicleDescStatus := vehicleFields[2].Descriptor()
	// vehicle.DefaultStatus holds the default value on creation for the status field.
	vehicle.DefaultStatus = vehicleDescStatus.Default.(string)
	// vehicleDescCreatedAt is the schema descriptor for created_at field.
	vehicleDescCreatedAt := vehicleFields[6].Descriptor()
	// vehicle.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicle.DefaultCreatedAt = vehicleDescCreatedAt.Default.(func() time.Time)
	// vehicleDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleDescUpdatedAt := vehicleFields[7].Descriptor()
	// vehicle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicle.DefaultUpdatedAt = vehicleDescUpdatedAt.Default.(func() time.Time)
	// vehicle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicle.UpdateDefaultUpdatedAt = vehicleDescUpdatedAt.UpdateDefault.(func() time.Time)
}
