// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuewentao/cheya/apps/vehicle/ent/schema"
	"github.com/xuewentao/cheya/apps/vehicle/ent/vehicle"
)

// VehicleCreate is the builder for creating a Vehicle entity.
type VehicleCreate struct {
	config
	mutation *VehicleMutation
	hooks    []Hook
}

// SetVin sets the "vin" field.
func (_c *VehicleCreate) SetVin(v string) *VehicleCreate {
	_c.mutation.SetVin(v)
	return _c
}

// SetLicensePlate sets the "license_plate" field.
func (_c *VehicleCreate) SetLicensePlate(v string) *VehicleCreate {
	_c.mutation.SetLicensePlate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VehicleCreate) SetStatus(v string) *VehicleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableStatus(v *string) *VehicleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_c *VehicleCreate) SetLastHeartbeat(v time.Time) *VehicleCreate {
	_c.mutation.SetLastHeartbeat(v)
	return _c
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableLastHeartbeat(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetLastHeartbeat(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *VehicleCreate) SetLocation(v *schema.Location) *VehicleCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetTelemetry sets the "telemetry" field.
func (_c *VehicleCreate) SetTelemetry(v map[string]interface{}) *VehicleCreate {
	_c.mutation.SetTelemetry(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VehicleCreate) SetCreatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableCreatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VehicleCreate) SetUpdatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableUpdatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the VehicleMutation object of the builder.
func (_c *VehicleCreate) Mutation() *VehicleMutation {
	return _c.mutation
}

// Save creates the Vehicle in the database.
func (_c *VehicleCreate) Save(ctx context.Context) (*Vehicle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VehicleCreate) SaveX(ctx context.Context) *Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VehicleCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := vehicle.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vehicle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vehicle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VehicleCreate) check() error {
	if _, ok := _c.mutation.Vin(); !ok {
		return &ValidationError{Name: "vin", err: errors.New(`ent: missing required field "Vehicle.vin"`)}
	}
	if v, ok := _c.mutation.Vin(); ok {
		if err := vehicle.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "Vehicle.vin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LicensePlate(); !ok {
		return &ValidationError{Name: "license_plate", err: errors.New(`ent: missing required field "Vehicle.license_plate"`)}
	}
	if v, ok := _c.mutation.LicensePlate(); ok {
		if err := vehicle.LicensePlateValidator(v); err != nil {
			return &ValidationError{Name: "license_plate", err: fmt.Errorf(`ent: validator failed for field "Vehicle.license_plate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Vehicle.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vehicle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vehicle.updated_at"`)}
	}
	return nil
}

func (_c *VehicleCreate) sqlSave(ctx context.Context) (*Vehicle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VehicleCreate) createSpec() (*Vehicle, *sqlgraph.CreateSpec) {
	var (
		_node = &Vehicle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vehicle.Table, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
		_node.Vin = value
	}
	if value, ok := _c.mutation.LicensePlate(); ok {
		_spec.SetField(vehicle.FieldLicensePlate, field.TypeString, value)
		_node.LicensePlate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(vehicle.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastHeartbeat(); ok {
		_spec.SetField(vehicle.FieldLastHeartbeat, field.TypeTime, value)
		_node.LastHeartbeat = &value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(vehicle.FieldLocation, field.TypeJSON, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Telemetry(); ok {
		_spec.SetField(vehicle.FieldTelemetry, field.TypeJSON, value)
		_node.Telemetry = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vehicle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// VehicleCreateBulk is the builder for creating many Vehicle entities in bulk.
type VehicleCreateBulk struct {
	config
	err      error
	builders []*VehicleCreate
}

// Save creates the Vehicle entities in the database.
func (_c *VehicleCreateBulk) Save(ctx context.Context) ([]*Vehicle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vehicle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VehicleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VehicleCreateBulk) SaveX(ctx context.Context) []*Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
