// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuewentao/cheya/apps/vehicle/ent/predicate"
	"github.com/xuewentao/cheya/apps/vehicle/ent/schema"
	"github.com/xuewentao/cheya/apps/vehicle/ent/vehicle"
)

// VehicleUpdate is the builder for updating Vehicle entities.
type VehicleUpdate struct {
	config
	hooks    []Hook
	mutation *VehicleMutation
}

// Where appends a list predicates to the VehicleUpdate builder.
func (_u *VehicleUpdate) Where(ps ...predicate.Vehicle) *VehicleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVin sets the "vin" field.
func (_u *VehicleUpdate) SetVin(v string) *VehicleUpdate {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableVin(v *string) *VehicleUpdate {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// SetLicensePlate sets the "license_plate" field.
func (_u *VehicleUpdate) SetLicensePlate(v string) *VehicleUpdate {
	_u.mutation.SetLicensePlate(v)
	return _u
}

// SetNillableLicensePlate sets the "license_plate" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableLicensePlate(v *string) *VehicleUpdate {
	if v != nil {
		_u.SetLicensePlate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VehicleUpdate) SetStatus(v string) *VehicleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableStatus(v *string) *VehicleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *VehicleUpdate) SetLastHeartbeat(v time.Time) *VehicleUpdate {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *VehicleUpdate) SetNillableLastHeartbeat(v *time.Time) *VehicleUpdate {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *VehicleUpdate) ClearLastHeartbeat() *VehicleUpdate {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetLocation sets the "location" field.
func (_u *VehicleUpdate) SetLocation(v *schema.Location) *VehicleUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *VehicleUpdate) ClearLocation() *VehicleUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetTelemetry sets the "telemetry" field.
func (_u *VehicleUpdate) SetTelemetry(v map[string]interface{}) *VehicleUpdate {
	_u.mutation.SetTelemetry(v)
	return _u
}

// ClearTelemetry clears the value of the "telemetry" field.
func (_u *VehicleUpdate) ClearTelemetry() *VehicleUpdate {
	_u.mutation.ClearTelemetry()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VehicleUpdate) SetUpdatedAt(v time.Time) *VehicleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VehicleMutation object of the builder.
func (_u *VehicleUpdate) Mutation() *VehicleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VehicleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VehicleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VehicleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VehicleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VehicleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vehicle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VehicleUpdate) check() error {
	if v, ok := _u.mutation.Vin(); ok {
		if err := vehicle.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "Vehicle.vin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicensePlate(); ok {
		if err := vehicle.LicensePlateValidator(v); err != nil {
			return &ValidationError{Name: "license_plate", err: fmt.Errorf(`ent: validator failed for field "Vehicle.license_plate": %w`, err)}
		}
	}
	return nil
}

func (_u *VehicleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vehicle.Table, vehicle.Columns, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
	}
	if value, ok := _u.mutation.LicensePlate(); ok {
		_spec.SetField(vehicle.FieldLicensePlate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(vehicle.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(vehicle.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(vehicle.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(vehicle.FieldLocation, field.TypeJSON, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(vehicle.FieldLocation, field.TypeJSON)
	}
	if value, ok := _u.mutation.Telemetry(); ok {
		_spec.SetField(vehicle.FieldTelemetry, field.TypeJSON, value)
	}
	if _u.mutation.TelemetryCleared() {
		_spec.ClearField(vehicle.FieldTelemetry, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vehicle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VehicleUpdateOne is the builder for updating a single Vehicle entity.
type VehicleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VehicleMutation
}

// SetVin sets the "vin" field.
func (_u *VehicleUpdateOne) SetVin(v string) *VehicleUpdateOne {
	_u.mutation.SetVin(v)
	return _u
}

// SetNillableVin sets the "vin" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableVin(v *string) *VehicleUpdateOne {
	if v != nil {
		_u.SetVin(*v)
	}
	return _u
}

// SetLicensePlate sets the "license_plate" field.
func (_u *VehicleUpdateOne) SetLicensePlate(v string) *VehicleUpdateOne {
	_u.mutation.SetLicensePlate(v)
	return _u
}

// SetNillableLicensePlate sets the "license_plate" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableLicensePlate(v *string) *VehicleUpdateOne {
	if v != nil {
		_u.SetLicensePlate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VehicleUpdateOne) SetStatus(v string) *VehicleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableStatus(v *string) *VehicleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *VehicleUpdateOne) SetLastHeartbeat(v time.Time) *VehicleUpdateOne {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *VehicleUpdateOne) SetNillableLastHeartbeat(v *time.Time) *VehicleUpdateOne {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *VehicleUpdateOne) ClearLastHeartbeat() *VehicleUpdateOne {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetLocation sets the "location" field.
func (_u *VehicleUpdateOne) SetLocation(v *schema.Location) *VehicleUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *VehicleUpdateOne) ClearLocation() *VehicleUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetTelemetry sets the "telemetry" field.
func (_u *VehicleUpdateOne) SetTelemetry(v map[string]interface{}) *VehicleUpdateOne {
	_u.mutation.SetTelemetry(v)
	return _u
}

// ClearTelemetry clears the value of the "telemetry" field.
func (_u *VehicleUpdateOne) ClearTelemetry() *VehicleUpdateOne {
	_u.mutation.ClearTelemetry()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VehicleUpdateOne) SetUpdatedAt(v time.Time) *VehicleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VehicleMutation object of the builder.
func (_u *VehicleUpdateOne) Mutation() *VehicleMutation {
	return _u.mutation
}

// Where appends a list predicates to the VehicleUpdate builder.
func (_u *VehicleUpdateOne) Where(ps ...predicate.Vehicle) *VehicleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VehicleUpdateOne) Select(field string, fields ...string) *VehicleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vehicle entity.
func (_u *VehicleUpdateOne) Save(ctx context.Context) (*Vehicle, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VehicleUpdateOne) SaveX(ctx context.Context) *Vehicle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VehicleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VehicleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VehicleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := vehicle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VehicleUpdateOne) check() error {
	if v, ok := _u.mutation.Vin(); ok {
		if err := vehicle.VinValidator(v); err != nil {
			return &ValidationError{Name: "vin", err: fmt.Errorf(`ent: validator failed for field "Vehicle.vin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicensePlate(); ok {
		if err := vehicle.LicensePlateValidator(v); err != nil {
			return &ValidationError{Name: "license_plate", err: fmt.Errorf(`ent: validator failed for field "Vehicle.license_plate": %w`, err)}
		}
	}
	return nil
}

func (_u *VehicleUpdateOne) sqlSave(ctx context.Context) (_node *Vehicle, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vehicle.Table, vehicle.Columns, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vehicle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vehicle.FieldID)
		for _, f := range fields {
			if !vehicle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vehicle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Vin(); ok {
		_spec.SetField(vehicle.FieldVin, field.TypeString, value)
	}
	if value, ok := _u.mutation.LicensePlate(); ok {
		_spec.SetField(vehicle.FieldLicensePlate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(vehicle.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(vehicle.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(vehicle.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(vehicle.FieldLocation, field.TypeJSON, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(vehicle.FieldLocation, field.TypeJSON)
	}
	if value, ok := _u.mutation.Telemetry(); ok {
		_spec.SetField(vehicle.FieldTelemetry, field.TypeJSON, value)
	}
	if _u.mutation.TelemetryCleared() {
		_spec.ClearField(vehicle.FieldTelemetry, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Vehicle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vehicle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
