// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VehiclesColumns holds the columns for the "vehicles" table.
	VehiclesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "vin", Type: field.TypeString, Unique: true},
		{Name: "license_plate", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "Offline"},
		{Name: "last_heartbeat", Type: field.TypeTime, Nullable: true},
		{Name: "location", Type: field.TypeJSON, Nullable: true},
		{Name: "telemetry", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VehiclesTable holds the schema information for the "vehicles" table.
	VehiclesTable = &schema.Table{
		Name:       "vehicles",
		Columns:    VehiclesColumns,
		PrimaryKey: []*schema.Column{VehiclesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "vehicle_status",
				Unique:  false,
				Columns: []*schema.Column{VehiclesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VehiclesTable,
	}
)

func init() {
}
