// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: vehicle/v1/vehicle.proto

package vehiclev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleStatus int32

const (
	VehicleStatus_VEHICLE_STATUS_UNSPECIFIED VehicleStatus = 0
	VehicleStatus_VEHICLE_STATUS_OFFLINE     VehicleStatus = 1
	VehicleStatus_VEHICLE_STATUS_ONLINE      VehicleStatus = 2
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "VEHICLE_STATUS_UNSPECIFIED",
		1: "VEHICLE_STATUS_OFFLINE",
		2: "VEHICLE_STATUS_ONLINE",
	}
	VehicleStatus_value = map[string]int32{
		"VEHICLE_STATUS_UNSPECIFIED": 0,
		"VEHICLE_STATUS_OFFLINE":     1,
		"VEHICLE_STATUS_ONLINE":      2,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_vehicle_v1_vehicle_proto_enumTypes[0].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_vehicle_v1_vehicle_proto_enumTypes[0]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{0}
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *GetVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,3,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=vehicle.v1.VehicleStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_v1_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

var File_vehicle_v1_vehicle_proto protoreflect.FileDescriptor

const file_vehicle_v1_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x18vehicle/v1/vehicle.proto\x12\n" +
	"vehicle.v1\"2\n" +
	"\x11GetVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"C\n" +
	"\x12GetVehicleResponse\x12-\n" +
	"\avehicle\x18\x01 \x01(\v2\x13.vehicle.v1.VehicleR\avehicle\"\x83\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\x03 \x01(\tR\flicensePlate\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.vehicle.v1.VehicleStatusR\x06status*f\n" +
	"\rVehicleStatus\x12\x1e\n" +
	"\x1aVEHICLE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VEHICLE_STATUS_OFFLINE\x10\x01\x12\x19\n" +
	"\x15VEHICLE_STATUS_ONLINE\x10\x022]\n" +
	"\x0eVehicleService\x12K\n" +
	"\n" +
	"GetVehicle\x12\x1d.vehicle.v1.GetVehicleRequest\x1a\x1e.vehicle.v1.GetVehicleResponseB\x92\x01\n" +
	"\x0ecom.vehicle.v1B\fVehicleProtoP\x01Z)github.com/cheya/api/vehicle/v1;vehiclev1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vehicle.V1\xca\x02\n" +
	"Vehicle\\V1\xe2\x02\x16Vehicle\\V1\\GPBMetadata\xea\x02\vVehicle::V1b\x06proto3"

var (
	file_vehicle_v1_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_v1_vehicle_proto_rawDescData []byte
)

func file_vehicle_v1_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_v1_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_v1_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_v1_vehicle_proto_rawDesc), len(file_vehicle_v1_vehicle_proto_rawDesc)))
	})
	return file_vehicle_v1_vehicle_proto_rawDescData
}

var file_vehicle_v1_vehicle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vehicle_v1_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vehicle_v1_vehicle_proto_goTypes = []any{
	(VehicleStatus)(0),         // 0: vehicle.v1.VehicleStatus
	(*GetVehicleRequest)(nil),  // 1: vehicle.v1.GetVehicleRequest
	(*GetVehicleResponse)(nil), // 2: vehicle.v1.GetVehicleResponse
	(*Vehicle)(nil),            // 3: vehicle.v1.Vehicle
}
var file_vehicle_v1_vehicle_proto_depIdxs = []int32{
	3, // 0: vehicle.v1.GetVehicleResponse.vehicle:type_name -> vehicle.v1.Vehicle
	0, // 1: vehicle.v1.Vehicle.status:type_name -> vehicle.v1.VehicleStatus
	1, // 2: vehicle.v1.VehicleService.GetVehicle:input_type -> vehicle.v1.GetVehicleRequest
	2, // 3: vehicle.v1.VehicleService.GetVehicle:output_type -> vehicle.v1.GetVehicleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vehicle_v1_vehicle_proto_init() }
func file_vehicle_v1_vehicle_proto_init() {
	if File_vehicle_v1_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_v1_vehicle_proto_rawDesc), len(file_vehicle_v1_vehicle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_v1_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_v1_vehicle_proto_depIdxs,
		EnumInfos:         file_vehicle_v1_vehicle_proto_enumTypes,
		MessageInfos:      file_vehicle_v1_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_v1_vehicle_proto = out.File
	file_vehicle_v1_vehicle_proto_goTypes = nil
	file_vehicle_v1_vehicle_proto_depIdxs = nil
}
