// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`            //VIN 车架号
	Tinestamp     string                 `protobuf:"bytes,2,opt,name=tinestamp,proto3" json:"tinestamp,omitempty"`                             //上报时间
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`                               // 位置信息
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`                                   // 速度 (km/h)
	BatteryLevel  float64                `protobuf:"fixed64,5,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // 电量/油量百分比 (0-100)
	EngineTemp    float64                `protobuf:"fixed64,6,opt,name=engine_temp,json=engineTemp,proto3" json:"engine_temp,omitempty"`       // 发动机温度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTelemetryRequest) Reset() {
	*x = UploadTelemetryRequest{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTelemetryRequest) ProtoMessage() {}

func (x *UploadTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTelemetryRequest.ProtoReflect.Descriptor instead.
func (*UploadTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *UploadTelemetryRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UploadTelemetryRequest) GetTinestamp() string {
	if x != nil {
		return x.Tinestamp
	}
	return ""
}

func (x *UploadTelemetryRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UploadTelemetryRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UploadTelemetryRequest) GetBatteryLevel() float64 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *UploadTelemetryRequest) GetEngineTemp() float64 {
	if x != nil {
		return x.EngineTemp
	}
	return 0
}

type UploadTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTelemetryResponse) Reset() {
	*x = UploadTelemetryResponse{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTelemetryResponse) ProtoMessage() {}

func (x *UploadTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTelemetryResponse.ProtoReflect.Descriptor instead.
func (*UploadTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *UploadTelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadTelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\ftelemetry.v1\"\xe5\x01\n" +
	"\x16UploadTelemetryRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x1c\n" +
	"\ttinestamp\x18\x02 \x01(\tR\ttinestamp\x122\n" +
	"\blocation\x18\x03 \x01(\v2\x16.telemetry.v1.LocationR\blocation\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12#\n" +
	"\rbattery_level\x18\x05 \x01(\x01R\fbatteryLevel\x12\x1f\n" +
	"\vengine_temp\x18\x06 \x01(\x01R\n" +
	"engineTemp\"M\n" +
	"\x17UploadTelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude2r\n" +
	"\x10TelemetryService\x12^\n" +
	"\x0fUploadTelemetry\x12$.telemetry.v1.UploadTelemetryRequest\x1a%.telemetry.v1.UploadTelemetryResponseB\xac\x01\n" +
	"\x10com.telemetry.v1B\x0eTelemetryProtoP\x01Z7github.com/xuewentao/cheya/api/telemetry/v1;telemetryv1\xa2\x02\x03TXX\xaa\x02\fTelemetry.V1\xca\x02\fTelemetry\\V1\xe2\x02\x18Telemetry\\V1\\GPBMetadata\xea\x02\rTelemetry::V1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(*UploadTelemetryRequest)(nil),  // 0: telemetry.v1.UploadTelemetryRequest
	(*UploadTelemetryResponse)(nil), // 1: telemetry.v1.UploadTelemetryResponse
	(*Location)(nil),                // 2: telemetry.v1.Location
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: telemetry.v1.UploadTelemetryRequest.location:type_name -> telemetry.v1.Location
	0, // 1: telemetry.v1.TelemetryService.UploadTelemetry:input_type -> telemetry.v1.UploadTelemetryRequest
	1, // 2: telemetry.v1.TelemetryService.UploadTelemetry:output_type -> telemetry.v1.UploadTelemetryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
