// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: api/vehicle/v1/vehicle.proto

package vehiclev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleStatus int32

const (
	VehicleStatus_VEHICLE_STATUS_UNSPECIFIED VehicleStatus = 0
	VehicleStatus_VEHICLE_STATUS_OFFLINE     VehicleStatus = 1
	VehicleStatus_VEHICLE_STATUS_ONLINE      VehicleStatus = 2
)

// Enum value maps for VehicleStatus.
var (
	VehicleStatus_name = map[int32]string{
		0: "VEHICLE_STATUS_UNSPECIFIED",
		1: "VEHICLE_STATUS_OFFLINE",
		2: "VEHICLE_STATUS_ONLINE",
	}
	VehicleStatus_value = map[string]int32{
		"VEHICLE_STATUS_UNSPECIFIED": 0,
		"VEHICLE_STATUS_OFFLINE":     1,
		"VEHICLE_STATUS_ONLINE":      2,
	}
)

func (x VehicleStatus) Enum() *VehicleStatus {
	p := new(VehicleStatus)
	*p = x
	return p
}

func (x VehicleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_vehicle_v1_vehicle_proto_enumTypes[0].Descriptor()
}

func (VehicleStatus) Type() protoreflect.EnumType {
	return &file_api_vehicle_v1_vehicle_proto_enumTypes[0]
}

func (x VehicleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatus.Descriptor instead.
func (VehicleStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{0}
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *GetVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type CreateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,2,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CreateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

type CreateVehicleReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleReponse) Reset() {
	*x = CreateVehicleReponse{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleReponse) ProtoMessage() {}

func (x *CreateVehicleReponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleReponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleReponse) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVehicleReponse) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin           string                 `protobuf:"bytes,2,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,3,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Status        VehicleStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=vehicle.v1.VehicleStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetStatus() VehicleStatus {
	if x != nil {
		return x.Status
	}
	return VehicleStatus_VEHICLE_STATUS_UNSPECIFIED
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         //页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //一页有多少
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *ListVehiclesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVehiclesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`                        //车辆列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` //总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vehicle_v1_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_api_vehicle_v1_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_vehicle_v1_vehicle_proto protoreflect.FileDescriptor

const file_api_vehicle_v1_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x1capi/vehicle/v1/vehicle.proto\x12\n" +
	"vehicle.v1\"2\n" +
	"\x11GetVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"C\n" +
	"\x12GetVehicleResponse\x12-\n" +
	"\avehicle\x18\x01 \x01(\v2\x13.vehicle.v1.VehicleR\avehicle\"M\n" +
	"\x14CreateVehicleRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\x02 \x01(\tR\flicensePlate\"5\n" +
	"\x14CreateVehicleReponse\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"\x83\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\x03 \x01(\tR\flicensePlate\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.vehicle.v1.VehicleStatusR\x06status\"F\n" +
	"\x13ListVehiclesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"h\n" +
	"\x14ListVehiclesResponse\x12/\n" +
	"\bvehicles\x18\x01 \x03(\v2\x13.vehicle.v1.VehicleR\bvehicles\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount*f\n" +
	"\rVehicleStatus\x12\x1e\n" +
	"\x1aVEHICLE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VEHICLE_STATUS_OFFLINE\x10\x01\x12\x19\n" +
	"\x15VEHICLE_STATUS_ONLINE\x10\x022\x85\x02\n" +
	"\x0eVehicleService\x12K\n" +
	"\n" +
	"GetVehicle\x12\x1d.vehicle.v1.GetVehicleRequest\x1a\x1e.vehicle.v1.GetVehicleResponse\x12S\n" +
	"\rCreateVehicle\x12 .vehicle.v1.CreateVehicleRequest\x1a .vehicle.v1.CreateVehicleReponse\x12Q\n" +
	"\fListVehicles\x12\x1f.vehicle.v1.ListVehiclesRequest\x1a .vehicle.v1.ListVehiclesResponseB+Z)github.com/cheya/api/vehicle/v1;vehiclev1b\x06proto3"

var (
	file_api_vehicle_v1_vehicle_proto_rawDescOnce sync.Once
	file_api_vehicle_v1_vehicle_proto_rawDescData []byte
)

func file_api_vehicle_v1_vehicle_proto_rawDescGZIP() []byte {
	file_api_vehicle_v1_vehicle_proto_rawDescOnce.Do(func() {
		file_api_vehicle_v1_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vehicle_v1_vehicle_proto_rawDesc), len(file_api_vehicle_v1_vehicle_proto_rawDesc)))
	})
	return file_api_vehicle_v1_vehicle_proto_rawDescData
}

var file_api_vehicle_v1_vehicle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_vehicle_v1_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_vehicle_v1_vehicle_proto_goTypes = []any{
	(VehicleStatus)(0),           // 0: vehicle.v1.VehicleStatus
	(*GetVehicleRequest)(nil),    // 1: vehicle.v1.GetVehicleRequest
	(*GetVehicleResponse)(nil),   // 2: vehicle.v1.GetVehicleResponse
	(*CreateVehicleRequest)(nil), // 3: vehicle.v1.CreateVehicleRequest
	(*CreateVehicleReponse)(nil), // 4: vehicle.v1.CreateVehicleReponse
	(*Vehicle)(nil),              // 5: vehicle.v1.Vehicle
	(*ListVehiclesRequest)(nil),  // 6: vehicle.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil), // 7: vehicle.v1.ListVehiclesResponse
}
var file_api_vehicle_v1_vehicle_proto_depIdxs = []int32{
	5, // 0: vehicle.v1.GetVehicleResponse.vehicle:type_name -> vehicle.v1.Vehicle
	0, // 1: vehicle.v1.Vehicle.status:type_name -> vehicle.v1.VehicleStatus
	5, // 2: vehicle.v1.ListVehiclesResponse.vehicles:type_name -> vehicle.v1.Vehicle
	1, // 3: vehicle.v1.VehicleService.GetVehicle:input_type -> vehicle.v1.GetVehicleRequest
	3, // 4: vehicle.v1.VehicleService.CreateVehicle:input_type -> vehicle.v1.CreateVehicleRequest
	6, // 5: vehicle.v1.VehicleService.ListVehicles:input_type -> vehicle.v1.ListVehiclesRequest
	2, // 6: vehicle.v1.VehicleService.GetVehicle:output_type -> vehicle.v1.GetVehicleResponse
	4, // 7: vehicle.v1.VehicleService.CreateVehicle:output_type -> vehicle.v1.CreateVehicleReponse
	7, // 8: vehicle.v1.VehicleService.ListVehicles:output_type -> vehicle.v1.ListVehiclesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_vehicle_v1_vehicle_proto_init() }
func file_api_vehicle_v1_vehicle_proto_init() {
	if File_api_vehicle_v1_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vehicle_v1_vehicle_proto_rawDesc), len(file_api_vehicle_v1_vehicle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vehicle_v1_vehicle_proto_goTypes,
		DependencyIndexes: file_api_vehicle_v1_vehicle_proto_depIdxs,
		EnumInfos:         file_api_vehicle_v1_vehicle_proto_enumTypes,
		MessageInfos:      file_api_vehicle_v1_vehicle_proto_msgTypes,
	}.Build()
	File_api_vehicle_v1_vehicle_proto = out.File
	file_api_vehicle_v1_vehicle_proto_goTypes = nil
	file_api_vehicle_v1_vehicle_proto_depIdxs = nil
}
